// CSE 154 ASCIIMation
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM =
"   o   \n" + 
"  /|\\  \n" + 
"  / \\  \n" + 
"=====\n" + 
" \\ o /\n" + 
"   |  \n" + 
"  / \\ \n" + 
"=====\n" + 
" _ o\n" + 
"  /\\\n" + 
" | \\\n" + 
"=====\n" + 
"\n" + 
"  __\\o\n" + 
" /) |\n" + 
"=====\n" + 
" __| \n" + 
"   \\o\n" + 
"   ( \\\n" + 
"=====\n" + 
" \\ /\n" + 
"  |\n" + 
" /o\\\n" + 
"=====\n" + 
"   |__\n" + 
" o/ \n" + 
" / )\n" + 
"=====\n" + 
"\n" + 
"  o/__\n" + 
" |   (\\\n" + 
"=====\n" + 
" o _\n" + 
" /\\\n" + 
" / |\n" + 
"=====\n" + 
" \\ o /\n" + 
"   |  \n" + 
"  / \\ \n" + 
"=====\n" + 
"  o   \n" + 
" /|\\  \n" + 
" / \\  \n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
